# Generated by Django 4.2.7 on 2024-02-21 18:05

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlignInferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/align_inference'))),
            ],
        ),
        migrations.CreateModel(
            name='FullWorkflowDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/full_workflow'))),
            ],
        ),
        migrations.CreateModel(
            name='InferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/inference'))),
            ],
        ),
        migrations.CreateModel(
            name='ParamInferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/param_inference'))),
            ],
        ),
    ]
