# Generated by Django 4.2.7 on 2024-01-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextflowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(unique=True, upload_to='nextflowFiles/uploads'),
        ),
    ]
