# Generated by Django 4.2.7 on 2024-01-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextflowApp', '0006_alter_document_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='nextflowFiles/uploads'),
        ),
    ]
