# Generated by Django 4.2.7 on 2024-01-18 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nextflowApp', '0010_alter_document_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filepath',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=models.CharField(max_length=100)),
        ),
    ]
