# Generated by Django 4.2.7 on 2024-01-18 15:31

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('nextflowApp', '0011_document_filepath_alter_document_docfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/inference'))),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
