# Generated by Django 4.2.7 on 2024-01-18 15:53

import django.core.validators
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('nextflowApp', '0012_inferencedocument_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencedocument',
            name='docfile',
            field=models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/inference'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['UU'])]),
        ),
    ]
