# Generated by Django 4.2.7 on 2024-01-18 17:12

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('nextflowApp', '0013_alter_inferencedocument_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencedocument',
            name='docfile',
            field=models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/inference')),
        ),
    ]
