# Generated by Django 4.2.7 on 2024-01-26 19:43

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('nextflowApp', '0016_aligninferencedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullWorkflowDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=pathlib.PurePosixPath('nextflowFiles/uploads/full_workflow'))),
            ],
        ),
    ]
